.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH git-gpg-remove 1  "git-gpg-remove " 
.SH NAME
git\-gpg\-remove \- Remove a file from encryption tracking
.SH SYNOPSIS
\fBgit\-gpg remove\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIFILES\fR> 
.SH DESCRIPTION
Remove a file from encryption tracking
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIFILES\fR>
File(s) to remove
