.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH git-gpg-hide 1  "git-gpg-hide " 
.SH NAME
git\-gpg\-hide \- Hide \- encrypt all tracked files
.SH SYNOPSIS
\fBgit\-gpg hide\fR [\fB\-\-remote\fR] [\fB\-\-gpg\-home\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Hide \- encrypt all tracked files
.SH OPTIONS
.TP
\fB\-\-remote\fR \fI<REMOTE>\fR [default: origin]
Git remote name
.TP
\fB\-\-gpg\-home\fR \fI<GPG_HOME>\fR
Key store directory (default: $HOME/.git\-gpg)
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
