.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH git-gpg-add 1  "git-gpg-add " 
.SH NAME
git\-gpg\-add \- Add a file to be encrypted
.SH SYNOPSIS
\fBgit\-gpg add\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIFILES\fR> 
.SH DESCRIPTION
Add a file to be encrypted
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIFILES\fR>
File(s) to add
