.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH git-gpg-show-repo-id 1  "git-gpg-show-repo-id " 
.SH NAME
git\-gpg\-show\-repo\-id \- Show the repository ID
.SH SYNOPSIS
\fBgit\-gpg show\-repo\-id\fR [\fB\-\-remote\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show the repository ID
.SH OPTIONS
.TP
\fB\-\-remote\fR \fI<REMOTE>\fR [default: origin]
Git remote name
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
